# Generated by Django 3.2.19 on 2023-07-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_race_size_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicitem',
            name='components',
            field=models.TextField(help_text='Text description of crafting components, if the item can be crafted.', null=True),
        ),
        migrations.AddField(
            model_name='magicitem',
            name='requirements',
            field=models.TextField(help_text='Text description of requirements to use the item.', null=True),
        ),
    ]
